<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>jenkinsType</name>
   <tag></tag>
   <elementGuidId>2ecc0f24-a425-4104-b4ce-b9df19c19933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[contains(text(),&quot;Jenkins&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
