<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mavenType</name>
   <tag></tag>
   <elementGuidId>0bd19c18-0063-43bc-ab80-e4c312aeaf46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[contains(text(),&quot;Maven&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
